### ISSUE TITLE
Export color coded Excel

### ISSUE THREAD

**Issue by jseaz73** [arcanistzed/mcc#22]
### Problem

when upgrading, I have been asked to go in and turn on & off the different modules to see what is broken / conflicting .... and Keeping track of that is a ... challenge when I have 85 active modules :-) 

### Solution

Would be great to have a way to keep track of the testing, makes notes etc ... 

My suggestion would be to make it exportable to excel or google sheets ... with the colors in the list ... then I could add a column for status or make notes about errors etc

**Comment by arcanistzed** [comment]
You could just use the source Google Sheets document that this is pulling data from.
