### ISSUE TITLE
Add column to detailed view for whether a module is active in the current world or not.

### ISSUE THREAD

**Issue by revilowaldow** [arcanistzed/mcc#6]
### Problem

Sometimes when looking at the full list of modules I want to only think about the ones that I have active in the currently active world. Add a way to sort (filter, or both) by whether the module is active in the current world. It would also be good if filtering is available to look at a chart for the active world specifically.

### Solution

Column in the detailed view page.

### Alternatives

Manually checking back and forth, obviously undesirable.

**Comment by revilowaldow** [comment]
Just found the ✅button.

**Comment by arcanistzed** [comment]
Yeah, it's a bit hard to see... It used to have a better icon (🎁 with a ✅), but I had to change it to a simple checkmark because it's not available on the older version of FontAwesome used by v9.
