### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'localize')

### ISSUE THREAD

**Issue by Aeristoka** [arcanistzed/mcc#7]
### Expected Behavior

Not having this error

### Current Behavior

![image](https://user-images.githubusercontent.com/7988297/187009491-4a62e32c-31c0-4173-bd8a-f1e2dbde2f17.png)

### Steps to Reproduce

1. Load into FoundryVTT
2. Enable Module Compatibility Checker
3. Open Browser Developer Tools
4. Observe error in Console tab

### Version

1.2.4

### Foundry VTT Version

9

### Operating System

Irrelevant

### Browser / App

Chrome

### Game System

dnd5e

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Thank you. I'm aware of the issue, but I'm currently camping, so I'll fix this on Monday.

**Comment by arcanistzed** [comment]
I cannot reproduce this issue unfortunately. If you are still experiencing it on v1.2.5, let me know.

**Comment by Aeristoka** [comment]
> I cannot reproduce this issue unfortunately. If you are still experiencing it on v1.2.5, let me know.

Absolutely still happens on v1.2.5

![image](https://user-images.githubusercontent.com/7988297/187333323-bb9065ac-d866-4400-b1ba-bfe10d0acc10.png)

![image](https://user-images.githubusercontent.com/7988297/187333345-00572c17-c49f-410e-a617-9c155ac3468b.png)
