### ISSUE TITLE
[Bug]: SyntaxError : Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by CatbotTsumi** [arcanistzed/mcc#8]
### Expected Behavior

First time using the module. Expected to not see an error.

### Current Behavior

I pressed the Module Compatibility Checker button in Module Management and it loaded for a little while before dropping an error. `SyntaxError: Unexpected token u in JSON at position 0` 

### Steps to Reproduce

I pressed the Module Compatibility Checker button in Module Management and it loaded for a little while before dropping an error. `SyntaxError: Unexpected token u in JSON at position 0` 

### Version

1.2.4

### Foundry VTT Version

9.269

### Operating System

Windows NT

### Browser / App

Native Electron App

### Game System

dnd5e (1.6.3)

### Modules Disabled

- [ ] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Could you install the Find the Culprit module and run it? Since you said that you don't have this issue with all other modules disabled, I'd like to find out which other module is causing this issue for you.

**Comment by CatbotTsumi** [comment]
Because you asked so nicely i was going to do exactly that... but oddly enough, starting up foundry again today, making sure the error still happens... it didnt. Its working properly now for some reason today. If it happens again i can reopen this and send you the culprit module info.
